# Generated by Django 4.0.5 on 2022-09-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_followers_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Profile',
        ),
    ]
