# Generated by Django 4.0.5 on 2022-06-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_alter_auctionlisting_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionstatus',
            old_name='status_title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
