# Generated by Django 4.0.5 on 2022-06-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_status_title_auctionstatus_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='status',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='AuctionStatus',
        ),
    ]
