# Generated by Django 4.0.5 on 2022-06-30 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlisting_listing_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionstatus'),
        ),
    ]
