# Generated by Django 4.0.5 on 2022-06-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auctionlisting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='status',
            field=models.CharField(default='open', max_length=6),
        ),
    ]
