# Generated by Django 4.0.5 on 2022-06-30 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auctionlisting_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='category',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='seller',
        ),
        migrations.DeleteModel(
            name='AuctionStatus',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentator',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='listing',
        ),
        migrations.DeleteModel(
            name='AuctionListing',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
