# Generated by Django 4.0.5 on 2022-06-30 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auctionlisting_auctionstatus_category_comment_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionstatus'),
        ),
    ]
