# Generated by Django 4.0.5 on 2022-07-10 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_bid_bid_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentator',
            new_name='reviewer',
        ),
    ]
